### ISSUE TITLE
Support for other branches of Edge (Beta, Dev, Canary)

### ISSUE THREAD

**Issue by NaitorStudios** [quachpas/PowerToys-Run-EdgeWorkspaces#2]
Could you please add this? Because I really don't use the Stable release...

**Comment by quachpas** [comment]
It's already supported. Does it not detect your installation?

**Comment by NaitorStudios** [comment]
Oh sorry, it was just slow the first time, now it appears to work correctly!

**Comment by quachpas** [comment]
Yes, the first time running the plugin it's a bit slow! Glad it's fixed
